databases:
  - name: haelthcentre
    databaseName: healthcenre
    user: staff

services:
  - type: web
    name: healthcentre
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn healthcentre.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
