# Generated by Django 4.2.3 on 2023-07-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('genotype', models.TextField(choices=[('AA', 'AA'), ('AC', 'AC'), ('AS', 'AS'), ('CC', 'CC'), ('SC', 'SC'), ('SS', 'SS')], max_length=2)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('allergies', models.BooleanField(default=False)),
                ('disability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('regNo', models.CharField(max_length=25, unique=True)),
                ('HRNo', models.CharField(max_length=25, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('others', 'others')], default='others', max_length=6)),
                ('Age', models.IntegerField()),
                ('mobileNo', models.CharField(max_length=20, unique=True)),
                ('birthDate', models.DateTimeField()),
                ('maritalStatus', models.CharField(choices=[('single', 'SINGLE'), ('married', 'MARRIED')], default='single', max_length=8)),
                ('kind', models.CharField(choices=[('Student', (('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'))), ('Staff', (('academic staff', 'Academic Staff'), ('non-academic staff', 'Non-academic Staff'))), ('visitor', 'Visitor'), ('unknown', 'Unknown')], default='unknown', max_length=19)),
                ('tribe', models.CharField(max_length=20)),
                ('stateOfOrigin', models.CharField(max_length=29)),
                ('nationality', models.CharField(max_length=150)),
                ('religion', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('kinName', models.CharField(max_length=150)),
                ('kinAddress', models.CharField(max_length=500)),
                ('kinMobile', models.CharField(max_length=20)),
                ('regStatus', models.BooleanField(default=False)),
                ('medInfo', models.ForeignKey(default='regNo', on_delete=django.db.models.deletion.CASCADE, related_name='med-info+', to='HMS.healthprofile')),
            ],
        ),
    ]
