# Generated by Django 4.2.3 on 2023-07-20 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthcentre_No', models.CharField(blank=True, max_length=12, null=True)),
                ('bloodGroup', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Unknown', 'UNKNOWN')], default='Unknown', max_length=7)),
                ('genotype', models.CharField(choices=[('AA', 'AA'), ('AC', 'AC'), ('AS', 'AS'), ('CC', 'CC'), ('SC', 'SC'), ('SS', 'SS'), ('Unknown', 'UNKNOWN')], default='Unknown', max_length=7)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('allergies', models.BooleanField(default=False)),
                ('disability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('matric_No', models.CharField(max_length=25, unique=True)),
                ('healthcentre_No', models.CharField(max_length=25, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'others')], default='Others', max_length=6)),
                ('Age', models.IntegerField()),
                ('mobileNo', models.CharField(max_length=20, unique=True)),
                ('birthDate', models.DateTimeField()),
                ('maritalStatus', models.CharField(choices=[('S', 'SINGLE'), ('M', 'MARRIED')], default='S', max_length=1)),
                ('kind', models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AC', 'Academic Staff'), ('NA', 'Non-academic Staff'), ('VR', 'Visitor'), ('Unknown', 'Unknown')], default='Unknown', max_length=7)),
                ('tribe', models.CharField(max_length=20)),
                ('stateOfOrigin', models.CharField(max_length=29)),
                ('nationality', models.CharField(max_length=150)),
                ('religion', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('kinName', models.CharField(max_length=150)),
                ('kinAddress', models.CharField(max_length=500)),
                ('kin_relationship', models.CharField(choices=[('cousin', 'Cousin'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('sister', 'Sister'), ('brother', 'Brother'), ('guardian', 'Guardian')], default='brother', max_length=8)),
                ('kinMobile', models.CharField(max_length=20)),
                ('regStatus', models.BooleanField(default=False)),
                ('health_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='HMS.healthprofile')),
            ],
        ),
    ]
