# Generated by Django 4.2.3 on 2023-07-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='HRNo',
            new_name='healthcentre_No',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='regNo',
            new_name='matric_No',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medInfo',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='healthcentre_No',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='health_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_info', to='HMS.healthprofile'),
        ),
        migrations.AddField(
            model_name='patient',
            name='kin_relationship',
            field=models.CharField(choices=[('cousin', 'Cousin'), ('spouse', 'Spouse'), ('parent', 'Parent'), ('sister', 'Sister'), ('brother', 'Brother'), ('guardian', 'Guardian')], default='brother', max_length=8),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='AB-', max_length=3),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AC', 'AC'), ('AS', 'AS'), ('CC', 'CC'), ('SC', 'SC'), ('SS', 'SS')], default='AA', max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='kind',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('AC', 'Academic Staff'), ('NA', 'Non-academic Staff'), ('VR', 'Visitor'), ('Unknown', 'Unknown')], default='Unknown', max_length=7),
        ),
        migrations.AlterField(
            model_name='patient',
            name='maritalStatus',
            field=models.CharField(choices=[('S', 'SINGLE'), ('M', 'MARRIED')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('Others', 'others')], default='Others', max_length=6),
        ),
    ]
